image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Deploy to S3
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:0.3.8
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'us-east-2'
              S3_BUCKET: 'poupe-site'
              LOCAL_PATH: 'src'

    - step:
        name: Invalidate CloudFront
        script:
          - pipe: atlassian/aws-cloudfront-invalidate:0.1.2
            variables: 
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'us-east-2'
              DISTRIBUTION_ID: $AWS_CLOUDFRONT_DISTRIBUTION
              PATHS: '/*'